name: docker-php74-apache-mysql57

services:
    app:
        build:
            context: ./
            args:
                HOST_UID: ${HOST_UID:-1000}
                HOST_GID: ${HOST_GID:-1000}
        volumes:
            - ../../src/trunk:/var/www/html/wordpress/wp-content/plugins/confirm-mode-form-contact-form-7
            - ./apache2:/etc/apache2/sites-enabled
            - ./php.ini:/usr/local/etc/php/php.ini
            - ./html:/var/www/html
        ports:
            - 80:80
            - 443:443
  
    mysql:
        image: mysql:8.0
        volumes:
            - ./my.cnf:/etc/mysql/conf.d/my.cnf
            - mysql:/var/lib/mysql
        environment:
            MYSQL_DATABASE: docker
            MYSQL_ALLOW_EMPTY_PASSWORD: yes
        ports:
            - 3306:3306

    mailpit:
        image: axllent/mailpit
        ports:
            - 8025:8025
            - 1025:1025

volumes:
    mysql:
